### ISSUE TITLE
Is each `next_instruction` invoked by validators via separate transactions?

### ISSUE THREAD

**Issue by enzoampil** [clockwork-xyz/clockwork#122]
Just wanted to confirm whether each `next_instruction` is invoked by validators via separate transactions, or are they typically bundled within a single transaction?

I'm asking because I have a use case where a `Thread` will have 3 separate instructions, and there are enough combined accounts in these instructions that bundling them into the same transaction would surely lead to "transaction size limit" issues (e.g. >40 accounts in total).

**Comment by nickgarfield** [comment]
Yeah just to be clear here though, they do pack as many instructions as they can into the same transaction. I've often seen 11 or 12 instructions make it into a single transaction. If your interested, the simulation + packing logic can be found in the plugin here: 

https://github.com/clockwork-xyz/clockwork/blob/15896115a65fdc02605495f31869cbe39f2b2f69/plugin/src/builders/thread_exec.rs#L75
