### ISSUE TITLE
PDA seeds helper function

### ISSUE THREAD

**Issue by nickgarfield** [clockwork-xyz/clockwork#59]
Create helper functions on all state accounts to quickly grab the PDA seeds for Anchor verification. 

<img width="444" alt="Screen Shot 2022-09-06 at 19 37 27" src="https://user-images.githubusercontent.com/8634334/188763646-8077d774-a392-46c6-9cca-798f5a7ce01b.png">

**Comment by anoushk1234** [comment]
So implement a function on each Account struct that takes necessary inputs and gives the seeds?

**Comment by nickgarfield** [comment]
Relevant thread: https://twitter.com/time_composer/status/1599123089077698561

**Comment by nickgarfield** [comment]
This feature really should be at the Anchor-level.

**Comment by nickgarfield** [comment]
Closing for now since Anchor will be updating the syntax around this in coming versions.

**Comment by anoushk1234** [comment]
hey @nickgarfield sorry for the delayed response, we can continue the discussion in the twitter thread
